### ISSUE TITLE
CIDR block / not escaped in Whitelist Get

### ISSUE THREAD

**Issue by jagregory** [akshaykarle/go-mongodbatlas#1]
I suspect this is the root cause of: https://github.com/akshaykarle/terraform-provider-mongodbatlas/issues/16

According to the MongoDB Atlas docs, the / in CIDR blocks should be URL encoded when requesting Whitelist resources: https://docs.atlas.mongodb.com/reference/api/whitelist/#get-the-entry-for-a-specific-address-in-a-group-s-ip-whitelist

> If the entry includes a subnet mask, use the URL-encoded value for the forward slash (/). For example, for an entry of 1.2.3.4/5, use 1.2.3.4%2F5.

Looking at the [whitelist tests](https://github.com/akshaykarle/go-mongodbatlas/blob/master/mongodbatlas/whitelist_test.go#L38), the mux stub is being set up incorrectly without the slash encoded.

```go
mux.HandleFunc("/api/atlas/v1.0/groups/123/whitelist/10.15.0.0/16", func(w http.ResponseWriter, r *http.Request) {
  assertMethod(t, "GET", r)
  fmt.Fprintf(w, `{"cidrBlock":"10.15.0.0/16","comment":"test","groupId":"123","ipAddress":"10.15.0.1"}`)
})
```

**Comment by akshaykarle** [comment]
Hey @jagregory looking into this now. Although I've not escaped the slash in the test, I did escape the path in the `Get` implementation of [whitelist](https://github.com/akshaykarle/go-mongodbatlas/blob/master/mongodbatlas/whitelist.go#L53-L54) itself:
```
	escapedIP := url.PathEscape(ip)
	path := fmt.Sprintf("%s/whitelist/%s", gid, escapedIP)
```

I'll continue looking into akshaykarle/terraform-provider-mongodbatlas#16 to see if there is something else I'm missing. Let me know if there is something else you may have noticed.
