### ISSUE TITLE
Add tag to go-http-digest-auth-client project

### ISSUE THREAD

**Issue by gordonbondon** [akshaykarle/go-mongodbatlas#13]
https://github.com/akshaykarle/go-http-digest-auth-client has issues disabled so I decided to create it here. 

We want to use `go-mongodbatlas` as dependency in our project. But go modules will always download `0.3.0` version and break auth because `go-http-digest-auth-client` has no tag on latest commit with headers fix.

**Comment by akshaykarle** [comment]
thanks to @hatemosphere this should be fixed now, can you try again @gordonbondon ?

**Comment by gordonbondon** [comment]
@akshaykarle still it would be nice to have a tag on latest commit. Currently we had to handcraft modules version because by default it downloads latest tag.

**Comment by akshaykarle** [comment]
Done, I've added the tag v0.3.1 and updated the repo- https://github.com/akshaykarle/go-mongodbatlas/commit/46d09d05974392fb50617416a38f8cd99baee30b

**Comment by gordonbondon** [comment]
Thanks!
